### ISSUE TITLE
Question: Can Lila be used with BanksiaGUI?

### ISSUE THREAD

**Issue by al3xandru** [StylexTV/Lila#1]
I have tried to add lila as an engine for BanksiaGUI, but I haven't been able to figure out how to configure it. Banksia returns an error "This engine doesn't support the selected protocol".

**Comment by AlexBrunetti** [comment]
For me it works fine. UCI protocol works correctly, so there's no reason to fail in Banksia.

Alex

**Comment by al3xandru** [comment]
@AlexBrunetti can you please share how you configured it? thank you

**Comment by AlexBrunetti** [comment]
Well, here there is only a jar file, Banksia can't run directly a jar file. You should write a batch file, call it for example lila.bat and write into it: java -jar "Lila 3.0.1 64-bit.jar" (or whatever name has your .jar file). Then install into Banksia lila.bat. Obviously you should have Java installed in your machine.

Edit: I've just seen you are a Java programmer so you already should know what do to :)

Alex

**Comment by al3xandru** [comment]
Ha ha... I have tried setting the command to "java -jar lila_3.jar" and hoped it will work. Next I tried the sh file and that still did not work. This is very odd.

My file:

```
#!/usr/bin/env bash
SCRIPTDIR=$(dirname "${BASH_SOURCE[0]}")
/usr/bin/java -jar "$SCRIPTDIR/lila_3.jar"
```

**Comment by AlexBrunetti** [comment]
What happens if you launch the script in your shell (not from Banksia)?

Alex

**Comment by al3xandru** [comment]
It displays what I'd expect: `Lila 3.0.1 by StylexTV`

**Comment by AlexBrunetti** [comment]
So it's only a matter of how to call the script in Banksia under Linux. I cannot help anymore but I can suggest you to join talkchess.com and ask in the forum, there're many Linux users there.

Alex

**Comment by al3xandru** [comment]
I have a clue what might be happening... the env in which Banksia runs the script might not be initialized completely. Sure go ahead an close this.
